using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace NukeAssalt.Tools.Config;

public static class LuauModuleWriter
{
    public static string BuildModule<T>(T document)
    {
        var node = JsonSerializer.SerializeToNode(document, ConfigLoader.SerializerOptions)
            ?? throw new InvalidOperationException("Unable to convert config document into a JSON node.");

        var builder = new StringBuilder();
        builder.AppendLine("--!strict");
        builder.AppendLine("-- Generated by NukeAssalt.Tools. Do not edit by hand.");
        builder.Append("return ");
        WriteNode(builder, node, 0);
        builder.AppendLine();

        return builder.ToString();
    }

    private static void WriteNode(StringBuilder builder, JsonNode? node, int indentLevel)
    {
        if (node is null)
        {
            builder.Append("nil");
            return;
        }

        switch (node)
        {
            case JsonObject jsonObject:
                WriteObject(builder, jsonObject, indentLevel);
                return;
            case JsonArray jsonArray:
                WriteArray(builder, jsonArray, indentLevel);
                return;
            case JsonValue jsonValue:
                builder.Append(jsonValue.ToJsonString());
                return;
            default:
                throw new NotSupportedException($"Unsupported node type: {node.GetType().Name}");
        }
    }

    private static void WriteObject(StringBuilder builder, JsonObject jsonObject, int indentLevel)
    {
        if (jsonObject.Count == 0)
        {
            builder.Append("{}");
            return;
        }

        builder.AppendLine("{");

        foreach (var property in jsonObject)
        {
            builder.Append(Indent(indentLevel + 1));
            builder.Append('[');
            builder.Append(JsonSerializer.Serialize(property.Key));
            builder.Append("] = ");
            WriteNode(builder, property.Value, indentLevel + 1);
            builder.AppendLine(",");
        }

        builder.Append(Indent(indentLevel));
        builder.Append('}');
    }

    private static void WriteArray(StringBuilder builder, JsonArray jsonArray, int indentLevel)
    {
        if (jsonArray.Count == 0)
        {
            builder.Append("{}");
            return;
        }

        builder.AppendLine("{");

        foreach (var item in jsonArray)
        {
            builder.Append(Indent(indentLevel + 1));
            WriteNode(builder, item, indentLevel + 1);
            builder.AppendLine(",");
        }

        builder.Append(Indent(indentLevel));
        builder.Append('}');
    }

    private static string Indent(int indentLevel) => new(' ', indentLevel * 4);
}
