using NukeAssalt.Tools.Config;

namespace NukeAssalt.Specs;

public sealed class GeneratorTests
{
    private readonly string _repoRoot = RepositoryRoot.Find();

    [Fact]
    public void Generator_produces_the_expected_luau_modules()
    {
        var bundle = ConfigLoader.LoadBundle(Path.Combine(_repoRoot, "data", "config"));
        var temporaryOutputRoot = Path.Combine(Path.GetTempPath(), $"nuke-assalt-{Guid.NewGuid():N}");
        Directory.CreateDirectory(temporaryOutputRoot);

        try
        {
            var generatedFiles = ConfigGenerationService.GenerateFiles(bundle, temporaryOutputRoot);
            var generatedFileNames = generatedFiles
                .Select(Path.GetFileName)
                .OrderBy(fileName => fileName, StringComparer.Ordinal)
                .ToArray();

            Assert.Equal(
                new[]
                {
                    "CatalogConfig.luau",
                    "EconomyConfig.luau",
                    "MatchConfig.luau",
                    "NetworkConfig.luau",
                    "RuntimeConfig.luau",
                },
                generatedFileNames);

            foreach (var filePath in generatedFiles)
            {
                var content = File.ReadAllText(filePath);

                Assert.Contains("-- Generated by NukeAssalt.Tools. Do not edit by hand.", content, StringComparison.Ordinal);
                Assert.Contains("return", content, StringComparison.Ordinal);
                Assert.Contains("[\"id\"]", content, StringComparison.Ordinal);
            }
        }
        finally
        {
            Directory.Delete(temporaryOutputRoot, recursive: true);
        }
    }
}
